---
title: C6255 |Microsoft 文件
ms.custom: ''
ms.date: 11/04/2016
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-ide-code-analysis
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C6255
helpviewer_keywords:
- C6255
ms.assetid: bb6430b2-782a-4410-a8e1-609df06007de
caps.latest.revision: 18
author: mikeblome
ms.author: mblome
manager: ghogen
ms.workload:
- multiple
ms.openlocfilehash: 78466fc5e835af01d52056f3ee085e0aef9fea99
ms.sourcegitcommit: 32f1a690fc445f9586d53698fc82c7debd784eeb
ms.translationtype: MT
ms.contentlocale: zh-TW
ms.lasthandoff: 12/22/2017
---
# <a name="c6255"></a>C6255
警告 C6255: _alloca 在失敗藉由引發堆疊溢位例外狀況。 請考慮改用 _malloca  
  
 這個警告指出呼叫`_alloca`已偵測到外部本機例外狀況處理。 `_alloca`應該一律從呼叫受保護的例外狀況處理常式範圍內因為它可以引發堆疊溢位例外狀況上失敗。 如果可能，而不是使用`_alloca`，請考慮使用`_malloca`這是更安全的版本`_alloca`。  
  
## <a name="example"></a>範例  
 下列程式碼會產生這個警告，因為`_alloca`可以產生例外狀況：  
  
```  
#include <windows.h>  
  
void f( )  
{  
  void *p = _alloca(10);  
  // code ...  
}  
  
```  
  
 若要修正這個警告，請使用`_malloca`並加入例外狀況處理常式，如下列程式碼所示：  
  
```  
#include <windows.h>  
#include <malloc.h>  
  
void f( )  
{  
  void *p;  
  int errcode;  
  __try   
  {  
    p = _malloca(10);  
    // code...  
    _freea(p);  
  }  
  __except( (GetExceptionCode() == STATUS_STACK_OVERFLOW ) ?  
              EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )  
  {  
    errcode = _resetstkoflw();  
    // code ...  
  }  
}  
```  
  
## <a name="see-also"></a>請參閱  
 [_malloca](/cpp/c-runtime-library/reference/malloca)